blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/snowdencubes/AtmoCraft/blob/main/SECURITY.md
    about: Please report security vulnerabilities privately.
